### ISSUE TITLE
Sistemare Drone Options in Network Initializer

### ISSUE THREAD

**Issue by samitos022** [ADVPROG-2024/Dronegowski#19]
Facendo cargo update e quindi aggiornando la dipendenza del git del WG ho notato che hanno modificato il drone togliendo il Drone Options e ora c'è un errore, quindi sarebbe da sistemare

**Comment by samitos022** [comment]
Fotse ho sistemato @JasnoorDharni, però controlla per sicurezza.

**Comment by JasnoorDharni** [comment]
Sì capo è apposto, ottimo lavoro!
chiudo l'issue
