### ISSUE TITLE
Controllare e sistemare i comportamenti per i diversi tipi di pacchetti ricevuti dal drone

### ISSUE THREAD

**Issue by samitos022** [ADVPROG-2024/Dronegowski#21]
Implementati:
- [x] Ack / Nack
- [x] Fragment
- [x] FloodRequest
- [x] FloodResponse

Da testare:
- [x] Ack / Nack
- [x] Fragment
- [x] FloodRequest
- [x] FloodResponse

**Comment by samitos022** [comment]
Ok, ma in quali casi di errore nell'invio di ack e nack bisogna affidarsi al SC?

**Comment by samitos022** [comment]
> If during the routing back of an Ack, Nack or FloodResponse packet we would encounter an error, we would send that packet directly to destination through the Simulation controller. This is necessary because our network doesn't have any other way to know what happens to a packet other than Acks and Nack, so they can't be lost.

Ok ho trovato questo, immagino che tutti i tipi di errore che non sono dropped, bisogna affidarsi al SC

**Comment by JasnoorDharni** [comment]
`if self.drop_packet() {
                                            // Nack: Dropped
                                            match self.forward_packet(self.packet_nack(packet.clone(), Nack {fragment_index: fragment.fragment_index, nack_type: NackType::Dropped})) {
                                                Ok(()) => {
                                                    // Nack packet inviato correttamente al prossimo nodo
                                                    println!("Nack packet inviato correttamente al prossimo nodo");
                                                },
                                                Err(err) => {
                                                    //qui dovremmo inviare il pacchetto alla destinazione tramite il SC, se non ho capito male il protocollo
                                                    panic!("{err:?}");
                                                },
                                            }
                                        }`

**Comment by JasnoorDharni** [comment]
chiedo scusa non è uscito bene il commento, comunque penso che anche nei casi di dropped vada messa questa cosa

**Comment by samitos022** [comment]
Ma scusa l'unica cosa che poteva essere droppata non era msgfragment? Quindi nack, ack, flood non droppano, giusto?

**Comment by JasnoorDharni** [comment]
Sìsì giusto, io intendevo che nel caso ci fosse un errore nell'invio di un nack di tipo dropped non bisogna panicare, ma usare il SC. Comunque penso che avevo malinteso io la tua domanda
