### ISSUE TITLE
Implementazione utile per il debbuging

### ISSUE THREAD

**Issue by samitos022** [ADVPROG-2024/Dronegowski#52]
Praticamente pensavo di implementare un metodo:

`fn set_debug_option(debug_option: DebugOption, active: bool) {
    self.debug_options.entry(debug_option).and_modify(active);
}`

che vada ad aggiornare l'hashmap self.debug_options che verrà aggiunto negli attributi del drone:

`pub struct MyDrone {
    ...
    drone_options: HashMap<DroneOption, bool>
}`

Di default tutti i DroneOptions sono settati su false

`// Metodi / Inizializzazione / Comportamenti al ricevimento di pacchetti o comandi
enum DebugOption {
    InitialitationDrone,
    ForwardPacketMethod,
    Ack,
    Nack,
    MsgFragment,
    ... altro,
}`

Esempio di cosa aggiungere nell'implementazione del drone.
`if debug_options.get(DroneOptions::Ack) { println!("[Drone {self.id}] Evento: Ack inviato correttamente!") }`

così, qunado vengono fatti i test case (anche per i vari SC, client, ...), all'inizio si possano impostare le parti del drone che si voglio debuggare, in modo da facilitare il lavoro di debug e la scrittura dei test.

Secondo me può essere una feature interessante e utile.

**Comment by JasnoorDharni** [comment]
approvo, molto utile
