### ISSUE TITLE
Rustfmt e clippy

### ISSUE THREAD

**Issue by samitos022** [ADVPROG-2024/Dronegowski#7]
Configure your IDE or editor to use rustfmt so that the code of from all team members is consistently formatted.
Furthermore, try to minimize the warnings produced by clippy (you can also configure your IDE or editor to show clippyʼs warnings): cargo clippy -- -W clippy::pedantic

**Comment by MarcoSigno03** [comment]
Thank you mate

**Comment by MarcoSigno03** [comment]
Penso l'abbiamo fatto tutti, a Pietro l'ho fatto io quindi chiudo l'issue

**Comment by MarcoSigno03** [comment]
Penso l'abbiamo fatto tutti, a Pietro l'ho fatto io quindi chiudo l'issue
